#!/bin/sh
cd "$(dirname "$0")"
PORT="${1:-8765}"
echo ""
echo "ISV wiki — offline kit (Python 3 HTTP server)"
echo "  Home       → http://127.0.0.1:${PORT}/index.html"
echo "  Simulator  → http://127.0.0.1:${PORT}/index.html#village-metering/village-simulator"
echo "  Workshop   → http://127.0.0.1:${PORT}/power-africa-2026-workshop-planning.html"
echo ""
echo "Frozen Village Simulator ships inside this repo (no second clone)."
echo "Do not open HTML via file:// — use this server."
echo "Live/dev sim (optional): sibling smart-village-simulator → npm start :5176"
echo "Press Ctrl+C to stop."
echo ""
exec python3 preview_server.py "$PORT"
